SELECT a.AUTHOR_ID, a.AUTHOR_NAME, CATEGORY, SUM(PRICE*SALES) TOTAL_SALES
FROM BOOK b, AUTHOR a, BOOK_SALES bs
WHERE a.AUTHOR_ID = b.AUTHOR_ID AND b.BOOK_ID = bs.BOOK_ID AND SALES_DATE LIKE '2022-01%'
GROUP BY a.AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC