SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(PRICE * SALES) TOTAL_SALES
FROM AUTHOR a, BOOK b, BOOK_SALES s
WHERE a.AUTHOR_ID = b.AUTHOR_ID AND b.BOOK_ID = s.BOOK_ID
AND SALES_DATE BETWEEN DATE('2022-01-01') AND DATE('2022-01-31')
GROUP BY a.AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;