SELECT o.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT * PRICE) TOTAL_SALES
FROM FOOD_ORDER o, FOOD_PRODUCT p
WHERE o.PRODUCT_ID = p.PRODUCT_ID
AND PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY o.PRODUCT_ID
ORDER BY TOTAL_SALES desc, o.PRODUCT_ID;