SELECT HISTORY_ID, ROUND(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) * (
    CASE
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90
        THEN (SELECT (1 - DISCOUNT_RATE * 0.01)
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상')
    
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30
        THEN (SELECT (1 - DISCOUNT_RATE * 0.01)
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상')
    
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7
        THEN (SELECT (1 - DISCOUNT_RATE * 0.01)
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상')
    
        ELSE 1
    END
)) FEE
FROM CAR_RENTAL_COMPANY_CAR c, CAR_RENTAL_COMPANY_RENTAL_HISTORY h
WHERE c.CAR_ID = h.CAR_ID
AND CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;