SELECT i.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO i, ITEM_TREE t
WHERE i.ITEM_ID = t.ITEM_ID
AND PARENT_ITEM_ID in (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE')
ORDER BY i.ITEM_ID desc;